services:
  floci:
    image: floci/floci:latest
    container_name: floci-aws
    ports:
      - "${FLOCI_PORT:-4568}:4566"
    networks:
      - infra-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3002}:3000"
    networks:
      - infra-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT:-9092}:9090"
    networks:
      - infra-net

networks:
  infra-net:
    driver: bridge
